# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordlist',
            options={'ordering': ['word']},
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(blank=True, verbose_name='Short Url'),
        ),
    ]
