# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20151228_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urlshortener.WordList'),
            preserve_default=False,
        ),
    ]
