# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_url_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordlist',
            options={'ordering': ['length']},
        ),
        migrations.AddField(
            model_name='wordlist',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
